/**
 * Core types for Predict.fun Market Maker
 */

export interface Config {
  apiBaseUrl: string;
  privateKey: string;
  rpcUrl?: string;
  predictAccountAddress?: string;
  apiKey?: string;
  jwtToken?: string;
  spread: number;
  minSpread?: number;
  maxSpread?: number;
  useValueSignal?: boolean;
  valueSignalWeight?: number;
  valueConfidenceMin?: number;
  orderSize: number;
  maxSingleOrderValue?: number;
  maxPosition: number;
  mmAccountEquityUsd?: number;
  mmMaxPositionPct?: number;
  mmOrderSizePct?: number;
  mmMaxSingleOrderPct?: number;
  mmMaxDailyLossPct?: number;
  mmAdaptiveParams?: boolean;
  mmSpreadVolWeight?: number;
  mmSpreadLiquidityWeight?: number;
  mmBookSpreadWeight?: number;
  mmVolEmaAlpha?: number;
  mmDepthEmaAlpha?: number;
  mmDepthLevels?: number;
  mmMinTopDepthShares?: number;
  mmMinTopDepthUsd?: number;
  mmDepthDropRatio?: number;
  mmDepthRefShares?: number;
  mmInventorySkewVolWeight?: number;
  mmInventorySkewDepthWeight?: number;
  mmIcebergEnabled?: boolean;
  mmIcebergRatio?: number;
  mmIcebergMaxChunkShares?: number;
  mmAdaptiveProfile?: 'AUTO' | 'CALM' | 'NORMAL' | 'VOLATILE';
  mmVolatilityCalmBps?: number;
  mmVolatilityVolatileBps?: number;
  mmIntervalVolatilityBps?: number;
  mmIntervalVolMultiplier?: number;
  mmProfileLiquidityLow?: number;
  mmProfileLiquidityHigh?: number;
  mmProfileSpreadMinCalm?: number;
  mmProfileSpreadMaxCalm?: number;
  mmProfileSpreadMinVolatile?: number;
  mmProfileSpreadMaxVolatile?: number;
  mmIcebergRequoteMs?: number;
  mmOrderRefreshMs?: number;
  mmOrderDepthUsage?: number;
  mmInventorySpreadWeight?: number;
  mmRepriceVolMultiplier?: number;
  mmCancelVolMultiplier?: number;
  mmNearTouchVolMultiplier?: number;
  mmAntiFillVolMultiplier?: number;
  mmNearTouchDepthSpeedBps?: number;
  mmNearTouchDepthSpeedMult?: number;
  mmAntiFillDepthSpeedMult?: number;
  mmOrderRiskVwapBps?: number;
  mmOrderRiskVwapShares?: number;
  mmOrderRiskVwapMult?: number;
  mmOrderRiskVwapLevels?: number;
  mmOrderRiskVwapFeeBps?: number;
  mmOrderRiskVwapSlippageBps?: number;
  mmPriceAccelBps?: number;
  mmPriceAccelWindowMs?: number;
  mmPressureMaxRatio?: number;
  mmPressureSpreadWeight?: number;
  mmPressureOffsetWeight?: number;
  mmAutoTuneEnabled?: boolean;
  mmAutoTuneWindowMs?: number;
  mmAutoTuneTargetFillRate?: number;
  mmAutoTuneTargetCancelRate?: number;
  mmAutoTuneStep?: number;
  mmAutoTuneMinMult?: number;
  mmAutoTuneMaxMult?: number;
  mmAutoTuneMinEvents?: number;
  mmAutoTuneUpdateMs?: number;
  mmAutoTuneTouchBufferWeight?: number;
  mmAutoTuneSizeWeight?: number;
  mmAutoTuneCancelWeight?: number;
  mmAutoTuneRepriceWeight?: number;
  mmCooldownVolMultiplier?: number;
  mmImbalanceLevels?: number;
  mmImbalanceWeight?: number;
  mmImbalanceMaxSkew?: number;
  mmImbalanceSpreadWeight?: number;
  mmDepthTrendDropRatio?: number;
  mmIcebergRequoteVolMultiplier?: number;
  mmIcebergRequoteDepthMultiplier?: number;
  mmProfileHoldMs?: number;
  mmProfileVolHysteresisBps?: number;
  mmIcebergFillPenalty?: number;
  mmIcebergPenaltyDecayMs?: number;
  mmOrderRefreshJitterPct?: number;
  mmBatchCancelEnabled?: boolean;
  mmBatchCancelMax?: number;
  mmBatchCancelDelayMs?: number;
  mmMinOrderLifetimeMs?: number;
  mmMinOrderLifetimePanicBypass?: boolean;
  mmCancelBudgetWindowMs?: number;
  mmCancelBudgetMax?: number;
  mmCancelBudgetCooldownMs?: number;
  mmCancelBudgetPanicBypass?: boolean;
  mmCancelBurstLimit?: number;
  mmCancelBurstWindowMs?: number;
  mmCancelBurstCooldownMs?: number;
  mmCancelBurstPanicBypass?: boolean;
  mmCancelBurstRetreatMs?: number;
  mmCancelBurstOnlyFar?: boolean;
  mmCancelBurstOnlyFarLayers?: number;
  mmCancelBurstLayerCap?: number;
  mmCancelMaxPerCycle?: number;
  mmCancelMaxPerCyclePanicBypass?: boolean;
  mmRiskThrottleEnabled?: boolean;
  mmRiskThrottleFillPenalty?: number;
  mmRiskThrottleCancelPenalty?: number;
  mmRiskThrottleNearTouchPenalty?: number;
  mmRiskThrottleWindowMs?: number;
  mmRiskThrottleDecayMs?: number;
  mmRiskThrottleMinFactor?: number;
  mmRiskThrottleMaxFactor?: number;
  mmRiskThrottleCoolOffMs?: number;
  mmRiskThrottleOnlyFarThreshold?: number;
  mmRiskThrottleOnlyFarLayers?: number;
  mmRiskThrottleLayerCap?: number;
  mmNearTouchBurstLimit?: number;
  mmNearTouchBurstWindowMs?: number;
  mmNearTouchBurstHoldMs?: number;
  mmNearTouchBurstSafeMode?: boolean;
  mmNearTouchBurstSafeModeMs?: number;
  mmFillBurstLimit?: number;
  mmFillBurstWindowMs?: number;
  mmFillBurstHoldMs?: number;
  mmFillBurstSafeMode?: boolean;
  mmFillBurstSafeModeMs?: number;
  mmMetricsPath?: string;
  mmMetricsFlushMs?: number;
  mmWsEnabled?: boolean;
  mmWsMaxAgeMs?: number;
  mmWsFallbackRest?: boolean;
  mmWsFallbackMinIntervalMs?: number;
  mmWsOnlyDirty?: boolean;
  mmWsDirtyMaxBatch?: number;
  mmWsIdleSleepMs?: number;
  mmWsGapMax?: number;
  mmWsGapCooldownMs?: number;
  mmWsGapReconnect?: boolean;
  mmWsHealthSpreadMultMax?: number;
  mmWsHealthSizeMultMin?: number;
  mmWsHealthLayerMultMin?: number;
  mmWsHealthHardThreshold?: number;
  mmWsHealthPauseMs?: number;
  mmWsHealthRecoverMs?: number;
  mmWsHealthCancelOnPause?: boolean;
  mmWsHealthCancelMultMax?: number;
  mmWsHealthRepriceMultMax?: number;
  mmWsHealthForceOnlyFar?: boolean;
  mmWsHealthOnlyFarLayers?: number;
  mmWsHealthMinIntervalMultMax?: number;
  mmWsHealthSizeScaleMin?: number;
  mmWsHealthSingleSide?: 'BUY' | 'SELL' | 'NONE';
  mmWsHealthSingleSideMode?: 'REMOTE' | 'NORMAL';
  mmWsHealthSingleSideOffsetBps?: number;
  mmWsHealthTouchBufferAddBps?: number;
  mmWsHealthSparseOdd?: boolean;
  mmWsHealthLayerCountCap?: number;
  mmWsHealthMaxOrdersMultMin?: number;
  mmWsHealthSoftCancelMultMax?: number;
  mmWsHealthHardCancelMultMax?: number;
  mmWsHealthRepriceBufferAddBps?: number;
  mmWsHealthCancelBufferAddBps?: number;
  mmWsHealthForceSafeMode?: boolean;
  mmWsHealthCancelConfirmMultMin?: number;
  mmWsHealthRepriceConfirmMultMin?: number;
  mmWsHealthDisableHedge?: boolean;
  mmWsHealthReadOnly?: boolean;
  mmWsHealthUltraSafeEnabled?: boolean;
  mmWsHealthUltraSafeSide?: 'BUY' | 'SELL' | 'NONE';
  mmWsHealthUltraSafeMode?: 'REMOTE' | 'NORMAL';
  mmWsHealthUltraSafeOffsetBps?: number;
  mmWsHealthUltraSafeFarLayers?: number;
  mmWsHealthUltraSafeSizeScale?: number;
  mmWsHealthEmergencyCancelAll?: boolean;
  mmWsHealthEmergencyCooldownMs?: number;
  mmWsHealthEmergencyIntervalMs?: number;
  mmWsHealthEmergencyRecoveryMs?: number;
  mmWsHealthEmergencyRecoveryRatio?: number;
  mmWsHealthEmergencyRecoveryMinRatio?: number;
  mmWsHealthEmergencyRecoverySteps?: number;
  mmWsHealthEmergencyRecoverySizeScaleMin?: number;
  mmWsHealthEmergencyRecoveryLayerCapMin?: number;
  mmWsHealthEmergencyRecoveryIntervalMultMax?: number;
  mmWsHealthEmergencyRecoverySingleSide?: 'BUY' | 'SELL' | 'NONE';
  mmWsHealthEmergencyRecoverySingleSideMode?: 'REMOTE' | 'NORMAL';
  mmWsHealthEmergencyRecoverySingleSideExitProgress?: number;
  mmWsHealthEmergencyRecoveryDepthMult?: number;
  mmWsHealthEmergencyRecoveryVolatilityMultMin?: number;
  mmWsHealthEmergencyRecoverySpreadAdd?: number;
  mmWsHealthEmergencyRecoveryIcebergRatio?: number;
  mmWsHealthEmergencyRecoveryCancelConfirmMultMin?: number;
  mmWsHealthEmergencyRecoveryMaxOrdersMultMin?: number;
  mmWsHealthEmergencyRecoveryRepriceConfirmMultMin?: number;
  mmWsHealthEmergencyRecoveryMaxNotionalMultMin?: number;
  mmWsHealthEmergencyRecoveryFarLayersMin?: number;
  mmWsHealthEmergencyRecoveryCancelIntervalMultMax?: number;
  mmWsHealthEmergencyRecoveryFarLayersMax?: number;
  mmWsHealthEmergencyRecoveryLayerConvergeEnabled?: boolean;
  mmWsHealthEmergencyRecoveryTemplateEnabled?: boolean;
  mmWsHealthEmergencyRecoverySingleSideOffsetBps?: number;
  mmWsHealthEmergencyRecoverySingleSideOffsetMinBps?: number;
  mmWsHealthEmergencyRecoveryFarLayerStep?: number;
  mmWsHealthEmergencyRecoverySingleSideAuto?: boolean;
  mmWsHealthEmergencyRecoverySingleSideImbalanceThreshold?: number;
  mmWsHealthEmergencyRecoveryMinIntervalMs?: number;
  mmWsHealthEmergencyRecoveryOffsetVolWeight?: number;
  mmWsHealthEmergencyRecoveryTemplateResetEnabled?: boolean;
  mmWsHealthEmergencyRecoverySingleSideLossWeight?: number;
  mmVenue?: 'predict' | 'polymarket';
  mmRequireJwt?: boolean;
  mmAsymSpreadWeight?: number;
  inventorySkewFactor?: number;
  cancelThreshold: number;
  repriceThreshold?: number;
  minOrderIntervalMs?: number;
  maxOrdersPerMarket?: number;
  maxDailyLoss?: number;
  mmDepthMinShares?: number;
  mmDepthTargetShares?: number;
  mmDepthPenaltyWeight?: number;
  mmDepthShareFactor?: number;
  mmAsymSpreadInventoryWeight?: number;
  mmAsymSpreadImbalanceWeight?: number;
  mmAsymSpreadMinFactor?: number;
  mmAsymSpreadMaxFactor?: number;
  mmQuoteOffsetBps?: number;
  mmTouchBufferBps?: number;
  mmTouchBufferVolWeight?: number;
  mmTouchBufferVolMaxBps?: number;
  mmTouchBufferDepthSpeedWeight?: number;
  mmTouchBufferDepthSpeedMaxBps?: number;
  mmTouchBufferFixedCents?: number;
  mmQuoteSecondLayer?: boolean;

  // ===== Phase 1: 增强模块配置 =====
  // 启用增强价差计算 (AS模型)
  mmEnhancedSpreadEnabled?: boolean;

  // AS模型权重 (0-1, 默认0.5表示50%权重)
  mmASModelWeight?: number;

  // AS模型参数
  mmASGamma?: number;      // 风险厌恶系数 (默认0.1)
  mmASLambda?: number;     // 订单到达速率 (默认1.0)
  mmASKappa?: number;      // 价格弹性 (默认1.5)
  mmASAlpha?: number;      // 库存影响 (默认0.5)
  mmASBeta?: number;       // 波动率影响 (默认0.3)
  mmASDelta?: number;      // 订单流影响 (默认0.2)

  // 库存分类阈值
  mmInventorySafeThreshold?: number;     // 安全阈值 (默认0.3)
  mmInventoryWarningThreshold?: number;  // 警告阈值 (默认0.5)
  mmInventoryDangerThreshold?: number;   // 危险阈值 (默认0.7)

  // ===== 统一做市商策略配置（整合所有优点） =====
  unifiedMarketMakerEnabled?: boolean;         // 启用统一做市商策略
  unifiedMarketMakerTolerance?: number;        // 对冲偏差容忍度 (0.05 = 5%)
  unifiedMarketMakerMinSize?: number;          // 最小对冲数量
  unifiedMarketMakerMaxSize?: number;          // 最大对冲数量
  unifiedMarketMakerBuySpreadBps?: number;      // Buy 单价差（基点，150 = 1.5%）- 备用
  unifiedMarketMakerSellSpreadBps?: number;     // Sell 单价差（基点，150 = 1.5%）- 备用
  unifiedMarketMakerHedgeSlippageBps?: number;  // 对冲滑点（基点，250 = 2.5%）
  unifiedMarketMakerAsyncHedging?: boolean;     // 启用异步对冲（不撤单）
  unifiedMarketMakerDualTrackMode?: boolean;   // 启用双轨并行模式
  unifiedMarketMakerDynamicOffsetMode?: boolean; // 启用动态偏移模式（第二档挂单）
  unifiedMarketMakerBuyOffsetBps?: number;     // Buy 单偏移量（基点，100 = 1%）
  unifiedMarketMakerSellOffsetBps?: number;    // Sell 单偏移量（基点，100 = 1%）
  unifiedMarketMakerMonitorTierOne?: boolean;  // 监控是否成为第一档（自动撤单重挂）

  mmFillRiskSpreadBps?: number;
  mmNearTouchPenaltyBps?: number;
  mmNearTouchPenaltyMaxBps?: number;
  mmNearTouchPenaltyDecayMs?: number;
  mmNearTouchSizePenalty?: number;
  mmFillPenaltyBps?: number;
  mmFillPenaltyMaxBps?: number;
  mmFillPenaltyDecayMs?: number;
  mmNoFillPassiveMs?: number;
  mmNoFillPenaltyBps?: number;
  mmNoFillPenaltyMaxBps?: number;
  mmNoFillRampMs?: number;
  mmNoFillSizePenalty?: number;
  mmNoFillTouchBps?: number;
  mmNoFillTouchMaxBps?: number;
  mmNoFillRepriceBps?: number;
  mmNoFillRepriceMaxBps?: number;
  mmNoFillCancelBps?: number;
  mmNoFillCancelMaxBps?: number;
  mmAggressiveMoveBps?: number;
  mmAggressiveMoveWindowMs?: number;
  mmHitWarningBps?: number;
  mmHitTopSizeMinShares?: number;
  mmHitTopSizeFactor?: number;
  mmHitDepthLevels?: number;
  mmHitDepthMinShares?: number;
  mmHitSpeedBps?: number;
  mmHitSpeedWindowMs?: number;
  mmHitSizeDropRatio?: number;
  mmHitSizeDropWindowMs?: number;
  mmVolatilityHighBps?: number;
  mmVolatilityLowBps?: number;
  mmIntervalProfileVolatileMultiplier?: number;
  mmIntervalProfileCalmMultiplier?: number;
  mmSpreadJumpBps?: number;
  mmSpreadJumpWindowMs?: number;
  mmMaxSharesPerOrder?: number;
  mmLayerCount?: number;
  mmLayerMinCount?: number;
  mmLayerVolatileCount?: number;
  mmLayerThinCount?: number;
  mmLayerPanicCount?: number;
  mmLayerPanicHoldMs?: number;
  mmLayerDepthTrendDrop?: number;
  mmLayerSpreadStepBps?: number;
  mmLayerStepBpsVolatileAdd?: number;
  mmLayerStepBpsThinAdd?: number;
  mmLayerStepBpsPanicAdd?: number;
  mmLayerDepthSpeedBps?: number;
  mmLayerSpeedCount?: number;
  mmLayerStepBpsSpeedAdd?: number;
  mmLayerDepthSpeedRetreatBps?: number;
  mmLayerRetreatCount?: number;
  mmLayerSpeedSizeMinFactor?: number;
  mmLayerRetreatSizeMinFactor?: number;
  mmLayerPanicSizeMinFactor?: number;
  mmLayerStepBpsRetreatAdd?: number;
  mmLayerPanicIntervalMult?: number;
  mmLayerPanicOnlyFar?: boolean;
  mmPanicSpreadAdd?: number;
  mmPanicTouchBufferBps?: number;
  mmPanicAutoTuneBoost?: number;
  mmPanicRestoreHoldMs?: number;
  mmPanicRestoreCount?: number;
  mmPanicRestoreSizeScale?: number;
  mmPanicRestoreIntervalMult?: number;
  mmRestoreExitRampMs?: number;
  mmRestoreExitRampSteps?: number;
  mmRestoreExitSizeRampMs?: number;
  mmRestoreExitSizeRampMinFactor?: number;
  mmPanicCooldownMult?: number;
  mmRestoreCooldownMult?: number;
  mmRestoreExitForceReprice?: boolean;
  mmPanicPauseMs?: number;
  mmPanicCleanupOnRestore?: boolean;
  mmPanicSingleSide?: 'BUY' | 'SELL' | 'NONE';
  mmPanicSingleSideMode?: 'REMOTE' | 'NORMAL';
  mmPanicSingleSideOffsetBps?: number;
  mmRestoreExitCleanupOnReprice?: boolean;
  mmRestoreExitMinDepthShares?: number;
  mmRestoreExitMinDepthUsd?: number;
  mmRestoreExitDepthCooldownMs?: number;
  mmRestoreLayerCountCap?: number;
  mmRestoreLayerStepBpsAdd?: number;
  mmPanicRestoreLayerCountCap?: number;
  mmPanicCooldownSizeScale?: number;
  mmRestoreCooldownSizeScale?: number;
  mmRestoreExitResync?: boolean;
  mmPanicStepBpsMult?: number;
  mmRestoreStepBpsMult?: number;
  mmSafeModeEnabled?: boolean;
  mmSafeModeVolBps?: number;
  mmSafeModeDepthTrend?: number;
  mmSafeModeSpreadMult?: number;
  mmSafeModeStepMult?: number;
  mmSafeModeCooldownMult?: number;
  mmSafeModeOnlyFar?: boolean;
  mmSafeModeSizeScale?: number;
  mmSafeModeSingleSide?: 'BUY' | 'SELL' | 'NONE';
  mmSafeModeSingleSideMode?: 'REMOTE' | 'NORMAL';
  mmSafeModeSingleSideOffsetBps?: number;
  mmSafeModeSpreadAdd?: number;
  mmSafeModeMinSpread?: number;
  mmSafeModeMaxSpread?: number;
  mmSafeModeDepthSpeedBps?: number;
  mmSafeModeLayerCountCap?: number;
  mmSafeModeRejectThin?: boolean;
  mmSafeModeCancelBufferAddBps?: number;
  mmSafeModeExitHoldMs?: number;
  mmSafeModeTouchBufferBps?: number;
  mmSafeModeOnlyFarLayers?: number;
  mmSafeModeMinIntervalMs?: number;
  mmSafeModeMaxSharesPerOrder?: number;
  mmSafeModeDepthUsageMult?: number;
  mmSafeModeDepthCapMult?: number;
  mmSafeModeNearTouchMult?: number;
  mmSafeModeAntiFillMult?: number;
  mmSafeModeNearTouchAddBps?: number;
  mmSafeModeCancelMult?: number;
  mmSafeModePauseMs?: number;
  mmSafeModeCancelThresholdMult?: number;
  mmSafeModeRepriceMult?: number;
  mmSafeModeRepriceBufferAddBps?: number;
  mmSafeModeRepriceConfirmMult?: number;
  mmSafeModeRecheckMult?: number;
  mmLayerRetreatOnlyFar?: boolean;
  mmLayerRetreatHoldMs?: number;
  mmLayerRetreatForceSingle?: boolean;
  mmLayerRestoreHoldMs?: number;
  mmLayerRestoreCount?: number;
  mmLayerRestoreRampMs?: number;
  mmLayerRestoreStepMs?: number;
  mmLayerRestoreStepCount?: number;
  mmLayerRestoreMinSpreadAdd?: number;
  mmLayerRestoreCancelBufferAddBps?: number;
  mmLayerStepBpsRestoreAdd?: number;
  mmLayerStepBpsRestoreExtra?: number;
  mmLayerRestoreIntervalMult?: number;
  mmLayerRestoreSizeMinFactor?: number;
  mmLayerRestoreMaxShares?: number;
  mmLayerRestoreOnlyFar?: boolean;
  mmLayerRestoreTouchBufferBps?: number;
  mmLayerRestoreNoNearTouch?: boolean;
  mmLayerGuardNearBps?: number;
  mmLayerGuardMinDepthShares?: number;
  mmLayerGuardMinDepthUsd?: number;
  mmLayerGuardDepthSpeedBps?: number;
  mmFastCancelBps?: number;
  mmFastCancelWindowMs?: number;
  mmFastCancelDepthSpeedBps?: number;
  mmFastCancelSpreadJumpBps?: number;
  mmDepthSpeedPauseBps?: number;
  mmDepthSpeedPauseMs?: number;
  mmProtectiveDepthSpeedBps?: number;
  mmProtectiveSpreadJumpBps?: number;
  mmProtectiveTemplateEnabled?: boolean;
  mmProtectiveHoldMs?: number;
  mmProtectiveMinIntervalMs?: number;
  mmProtectiveLayerCountCap?: number;
  mmProtectiveOnlyFar?: boolean;
  mmProtectiveForceSingle?: boolean;
  mmProtectiveSingleSide?: 'BUY' | 'SELL' | 'NONE';
  mmProtectiveSingleSideMode?: 'NORMAL' | 'REMOTE';
  mmProtectiveSingleSideOffsetBps?: number;
  mmProtectiveSingleSideAuto?: boolean;
  mmProtectiveSingleSideImbalanceThreshold?: number;
  mmProtectiveSizeScale?: number;
  mmProtectiveTouchBufferAddBps?: number;
  mmLayerRestoreNearTouchBps?: number;
  mmLayerRestoreForceRefresh?: boolean;
  mmLayerRestoreForceCleanup?: boolean;
  mmLayerRestoreNearTouchMult?: number;
  mmLayerRestoreNearTouchAddBps?: number;
  mmLayerRestoreCancelMult?: number;
  mmLayerRestoreExitCleanup?: boolean;
  mmLayerRestoreExitCooldownMs?: number;
  mmLayerRestoreExitImmediateRequote?: boolean;
  mmLayerRestoreSizeScale?: number;
  mmLayerRestoreDisableHedge?: boolean;
  mmLayerRestoreDisablePartialHedge?: boolean;
  mmLayerRestoreSparseOdd?: boolean;
  mmLayerSizeDecay?: number;
  mmLayerAllowBelowMinShares?: boolean;
  mmDepthSpeedWindowMs?: number;
  mmActionBurstLimit?: number;
  mmActionBurstWindowMs?: number;
  mmActionBurstCooldownMs?: number;
  mmActionBurstRestoreHoldMs?: number;
  mmSizeInventoryWeight?: number;
  mmSizeImbalanceWeight?: number;
  mmSizeMinFactor?: number;
  mmSizeMaxFactor?: number;
  mmSizeVolWeight?: number;
  mmSizeDepthSpeedWeight?: number;
  mmSoftCancelBps?: number;
  mmHardCancelBps?: number;
  mmSoftCancelCooldownMs?: number;
  mmHardCancelCooldownMs?: number;
  mmHoldNearTouchMs?: number;
  mmHoldNearTouchMaxBps?: number;
  mmRepriceBufferBps?: number;
  mmRepriceConfirmMs?: number;
  mmCancelBufferBps?: number;
  mmCancelConfirmMs?: number;
  mmPartialFillShares?: number;
  mmPartialFillPenalty?: number;
  mmPartialFillPenaltyDecayMs?: number;
  mmPartialFillHedge?: boolean;
  mmPartialFillHedgeMaxShares?: number;
  mmPartialFillHedgeSlippageBps?: number;
  mmCancelRecheckMs?: number;
  mmRepriceRecheckMs?: number;
  mmRecheckCooldownMs?: number;
  mmFillSlowdownWindowMs?: number;
  mmFillSlowdownFactor?: number;
  mmFillSlowdownMaxMultiplier?: number;
  mmAutoSizeOnFill?: boolean;
  mmAutoSizeOnFillDecayMs?: number;
  mmAutoSizeMinFactor?: number;
  mmDynamicCancelOnFill?: boolean;
  mmDynamicCancelBoost?: number;
  mmDynamicCancelDecayMs?: number;
  mmDynamicCancelMaxBoost?: number;
  mmOnlyPointsMarkets?: boolean;
  mmPointsMinOnly?: boolean;
  mmPointsMinMultiplier?: number;
  mmPointsPrioritize?: boolean; // 是否优先做积分市场
  mmPointsOptimization?: boolean; // 是否启用积分优化
  mmPointsV2Optimizer?: boolean; // 是否启用 V2 优化器（极致优化）
  mmPointsAssumeActive?: boolean;
  mmPointsMinShares?: number;
  mmPointsMaxSpreadCents?: number;
  mmPointsMaxSpread?: number;
  antiFillBps?: number;
  nearTouchBps?: number;
  cooldownAfterCancelMs?: number;
  volatilityPauseBps?: number;
  volatilityLookbackMs?: number;
  pauseAfterVolatilityMs?: number;
  hedgeOnFill?: boolean;
  hedgeTriggerShares?: number;
  hedgeMode?: 'FLATTEN' | 'CROSS' | 'NONE';
  hedgeMaxSlippageBps?: number;
  crossPlatformEnabled?: boolean;
  crossPlatformMinProfit?: number;
  crossPlatformMinSimilarity?: number;
  crossPlatformAutoExecute?: boolean;
  crossPlatformRequireConfirm?: boolean;
  crossPlatformMaxMatches?: number;
  crossPlatformTransferCost?: number;
  crossPlatformSlippageBps?: number;
  crossPlatformMaxShares?: number;
  crossPlatformDepthLevels?: number;
  crossPlatformMaxVwapLevels?: number;
  crossPlatformMaxVwapDeviationBps?: number;
  crossPlatformWsRealtime?: boolean;
  crossPlatformWsRealtimeIntervalMs?: number;
  crossPlatformWsRealtimeMaxBatch?: number;
  crossPlatformWsRealtimeQuiet?: boolean;
  crossPlatformWsRealtimeFallbackEnabled?: boolean;
  crossPlatformWsRealtimeFallbackIntervalMs?: number;
  crossPlatformWsRealtimeFallbackMaxMarkets?: number;
  crossPlatformWsRealtimeFallbackStaleMs?: number;
  crossPlatformExecutionVwapCheck?: boolean;
  crossPlatformPriceDriftBps?: number;
  crossPlatformPreSubmitDriftBps?: number;
  crossPlatformPreSubmitVwapBps?: number;
  crossPlatformPreSubmitProfitBps?: number;
  crossPlatformPreSubmitProfitUsd?: number;
  crossPlatformPreSubmitLegVwapSpreadBps?: number;
  crossPlatformPreSubmitTotalCostBps?: number;
  crossPlatformPreSubmitLegCostSpreadBps?: number;
  crossPlatformPreSubmitRecheckMs?: number;
  crossPlatformPreSubmitGlobal?: boolean;
  crossPlatformShadowMinProfitUsd?: number;
  crossPlatformShadowMinProfitBps?: number;
  crossPlatformShadowImpactBps?: number;
  crossPlatformShadowImpactPerLevelBps?: number;
  crossHedgeSimilarityWeight?: number;
  crossHedgeDepthWeight?: number;
  crossHedgeMinDepthUsd?: number;

  // ==================== 完美对冲策略配置 ====================
  perfectHedgeEnabled?: boolean;              // 启用完美对冲策略
  perfectHedgeTolerance?: number;             // 对冲偏差容忍度（0.05 = 5%）
  perfectHedgeMinSize?: number;               // 最小对冲数量（股）
  perfectHedgeMaxSize?: number;               // 最大对冲数量（股）
  perfectHedgeAutoBalance?: boolean;          // 自动平衡 YES/NO 比例
  perfectHedgeBalanceSlippageBps?: number;    // 平衡滑点（基点）

  crossPlatformAdaptiveSize?: boolean;
  crossPlatformMinDepthShares?: number;
  crossPlatformMinDepthUsd?: number;
  crossPlatformMinNotionalUsd?: number;
  crossPlatformMinProfitUsd?: number;
  crossPlatformMinProfitBps?: number;
  crossPlatformMinProfitImpactMult?: number;
  crossPlatformMissingVwapPenaltyBps?: number;
  crossPlatformVolatilityBps?: number;
  crossPlatformVolatilityLookbackMs?: number;
  crossPlatformTokenMaxFailures?: number;
  crossPlatformTokenFailureWindowMs?: number;
  crossPlatformTokenCooldownMs?: number;
  crossPlatformMetricsLogMs?: number;
  crossPlatformDepthUsage?: number;
  crossPlatformMinTopDepthShares?: number;
  crossPlatformMinTopDepthUsd?: number;
  crossPlatformTopDepthUsage?: number;
  crossPlatformMaxNotional?: number;
  crossPlatformRecheckMs?: number;
  crossPlatformRecheckDeviationBps?: number;
  crossPlatformRecheckDriftBps?: number;
  crossPlatformStabilitySamples?: number;
  crossPlatformStabilityIntervalMs?: number;
  crossPlatformStabilityBps?: number;
  crossPlatformPostTradeDriftBps?: number;
  crossPlatformAbortPostTradeDriftBps?: number;
  crossPlatformAbortCooldownMs?: number;
  crossPlatformFailurePauseMs?: number;
  crossPlatformFailurePauseMaxMs?: number;
  crossPlatformFailurePauseBackoff?: number;
  crossPlatformFailureRateWindowMs?: number;
  crossPlatformFailureRateMinAttempts?: number;
  crossPlatformFailureRateThreshold?: number;
  crossPlatformFailureRateTightenMax?: number;
  crossPlatformFailureRateStabilitySamplesAdd?: number;
  crossPlatformFailureRateStabilityIntervalAddMs?: number;
  crossPlatformFailureRateStabilityMaxSamples?: number;
  crossPlatformFailureRateStabilityMaxIntervalMs?: number;
  crossPlatformReasonPreflightPenalty?: number;
  crossPlatformReasonExecutionPenalty?: number;
  crossPlatformReasonPostTradePenalty?: number;
  crossPlatformReasonHedgePenalty?: number;
  crossPlatformAutoTune?: boolean;
  crossPlatformAutoTuneMinFactor?: number;
  crossPlatformAutoTuneMaxFactor?: number;
  crossPlatformAutoTuneUp?: number;
  crossPlatformAutoTuneDown?: number;
  crossPlatformTokenMinScore?: number;
  crossPlatformTokenScoreOnSuccess?: number;
  crossPlatformTokenScoreOnFailure?: number;
  crossPlatformTokenScoreOnVolatility?: number;
  crossPlatformTokenScoreOnPostTrade?: number;
  crossPlatformPlatformMinScore?: number;
  crossPlatformPlatformScoreOnSuccess?: number;
  crossPlatformPlatformScoreOnFailure?: number;
  crossPlatformPlatformScoreOnVolatility?: number;
  crossPlatformPlatformScoreOnPostTrade?: number;
  crossPlatformPlatformScoreOnSpread?: number;
  crossPlatformLegDriftSpreadBps?: number;
  crossPlatformLegVwapDeviationBps?: number;
  crossPlatformLegMinDepthUsd?: number;
  crossPlatformLegDeviationSoftBps?: number;
  crossPlatformLegDeviationSpreadBps?: number;
  crossPlatformLegDepthUsageMax?: number;
  crossPlatformLegDepthRatioMin?: number;
  crossPlatformLegDepthRatioSoft?: number;
  crossPlatformLegDepthRatioShrinkMinFactor?: number;
  crossPlatformDepthRatioPenaltyUp?: number;
  crossPlatformDepthRatioPenaltyDown?: number;
  crossPlatformDepthRatioPenaltyMax?: number;
  crossPlatformConsistencySamples?: number;
  crossPlatformConsistencyIntervalMs?: number;
  crossPlatformConsistencyVwapBps?: number;
  crossPlatformConsistencyVwapDriftBps?: number;
  crossPlatformConsistencyDepthRatioMin?: number;
  crossPlatformConsistencyDepthRatioDrift?: number;
  crossPlatformQualityProfitMult?: number;
  crossPlatformQualityProfitMax?: number;
  crossPlatformConsistencyFailLimit?: number;
  crossPlatformConsistencyFailWindowMs?: number;
  crossPlatformConsistencyDegradeMs?: number;
  crossPlatformConsistencyPenalty?: number;
  crossPlatformConsistencyUseDegradeProfile?: boolean;
  crossPlatformConsistencyOrderType?: 'FOK' | 'FAK' | 'GTC' | 'GTD' | '';
  crossPlatformConsistencyTemplateEnabled?: boolean;
  crossPlatformConsistencyTemplateDepthUsage?: number;
  crossPlatformConsistencyTemplateSlippageBps?: number;
  crossPlatformConsistencyTemplateMaxVwapLevels?: number;
  crossPlatformConsistencyTemplateMinProfitBps?: number;
  crossPlatformConsistencyTemplateMinProfitUsd?: number;
  crossPlatformConsistencyTemplateMinNotionalUsd?: number;
  crossPlatformConsistencyTemplateChunkFactor?: number;
  crossPlatformConsistencyTemplateChunkDelayMs?: number;
  crossPlatformConsistencyTemplateForceSequential?: boolean;
  crossPlatformConsistencyTemplateUseFok?: boolean;
  crossPlatformConsistencyTemplateLimitOrders?: boolean;
  crossPlatformConsistencyTemplateDisableBatch?: boolean;
  crossPlatformConsistencyTemplateTightenUp?: number;
  crossPlatformConsistencyTemplateTightenDown?: number;
  crossPlatformConsistencyTemplateTightenMax?: number;
  crossPlatformConsistencyTemplateTightenMin?: number;
  crossPlatformConsistencyRateLimitMs?: number;
  crossPlatformConsistencyRateLimitThreshold?: number;
  crossPlatformConsistencyRateLimitWindowMs?: number;
  crossPlatformAvoidHours?: number[];
  crossPlatformAvoidHoursAuto?: boolean;
  crossPlatformAvoidHoursDecayDays?: number;
  crossPlatformAvoidHoursMode?: 'BLOCK' | 'TEMPLATE';
  crossPlatformAvoidHoursModeAuto?: boolean;
  crossPlatformAvoidHoursBlockScore?: number;
  crossPlatformAvoidHoursTemplateScore?: number;
  crossPlatformAvoidHoursTemplateFactor?: number;
  crossPlatformWsHealthTightenMax?: number;
  crossPlatformWsHealthChunkDelayMaxMs?: number;
  crossPlatformWsHealthChunkFactorMin?: number;
  crossPlatformConsistencyCooldownMs?: number;
  crossPlatformConsistencyCooldownThreshold?: number;
  crossPlatformConsistencyCooldownWindowMs?: number;
  crossPlatformConsistencyPressureUp?: number;
  crossPlatformConsistencyPressureDown?: number;
  crossPlatformConsistencyPressureDecayMs?: number;
  crossPlatformConsistencyPressureTightenMax?: number;
  crossPlatformConsistencyPressureRetryDelayMs?: number;
  crossPlatformConsistencyPressureCooldownMaxMs?: number;
  crossPlatformConsistencyPressureSizeMin?: number;
  crossPlatformConsistencyPressureDegradeThreshold?: number;
  crossPlatformConsistencyPressureDegradeMs?: number;
  crossPlatformConsistencyPressureUseDegradeProfile?: boolean;
  crossPlatformConsistencyPressureHardThreshold?: number;
  crossPlatformConsistencyPressureHardFactor?: number;
  crossPlatformWsHealthHardThreshold?: number;
  crossPlatformWsHealthHardFactor?: number;
  crossPlatformHardGateDegradeMs?: number;
  crossPlatformHardGateUseDegradeProfile?: boolean;
  crossPlatformHardGateRateLimitMs?: number;
  crossPlatformHardGateAutoApplyFix?: boolean;
  crossPlatformHardGateAutoUltra?: boolean;
  crossPlatformAllowlistTokens?: string[];
  crossPlatformBlocklistTokens?: string[];
  crossPlatformAllowlistPlatforms?: string[];
  crossPlatformBlocklistPlatforms?: string[];
  crossPlatformChunkMaxShares?: number;
  crossPlatformChunkMaxNotional?: number;
  crossPlatformChunkDelayMs?: number;
  crossPlatformChunkPreflight?: boolean;
  crossPlatformChunkAutoTune?: boolean;
  crossPlatformChunkFactorMin?: number;
  crossPlatformChunkFactorMax?: number;
  crossPlatformChunkFactorUp?: number;
  crossPlatformChunkFactorDown?: number;
  crossPlatformChunkDelayAutoTune?: boolean;
  crossPlatformChunkDelayMinMs?: number;
  crossPlatformChunkDelayMaxMs?: number;
  crossPlatformChunkDelayUpMs?: number;
  crossPlatformChunkDelayDownMs?: number;
  crossPlatformPlatformMaxFailures?: number;
  crossPlatformPlatformFailureWindowMs?: number;
  crossPlatformPlatformCooldownMs?: number;
  crossPlatformAutoBlocklist?: boolean;
  crossPlatformAutoBlocklistCooldownMs?: number;
  crossPlatformAutoBlocklistScore?: number;
  crossPlatformGlobalCooldownMs?: number;
  crossPlatformGlobalMinQuality?: number;
  crossPlatformStatePath?: string;
  crossPlatformMetricsPath?: string;
  crossPlatformMetricsFlushMs?: number;
  crossPlatformOrderType?: 'FOK' | 'FAK' | 'GTC' | 'GTD';
  crossPlatformOrderTypeFallback?: string[];
  crossPlatformFallbackMode?: 'AUTO' | 'SEQUENTIAL' | 'SINGLE_LEG';
  crossPlatformBatchOrders?: boolean;
  crossPlatformBatchMax?: number;
  crossPlatformUseFok?: boolean;
  crossPlatformParallelSubmit?: boolean;
  crossPlatformAutoSequentialDriftBps?: number;
  crossPlatformAutoSequentialVwapBps?: number;
  crossPlatformAutoFokDriftBps?: number;
  crossPlatformAutoFokVwapBps?: number;
  crossPlatformAutoSingleLegDriftBps?: number;
  crossPlatformAutoSingleLegVwapBps?: number;
  crossPlatformAutoFallbackOnFailure?: boolean;
  crossPlatformAutoFallbackSteps?: string[];
  crossPlatformFailureSizeFactorDown?: number;
  crossPlatformFailureSizeFactorUp?: number;
  crossPlatformFailureSizeFactorMin?: number;
  crossPlatformFailureSizeFactorMax?: number;
  crossPlatformFailureProfitMultDown?: number;
  crossPlatformFailureProfitMultUp?: number;
  crossPlatformFailureProfitMultMin?: number;
  crossPlatformFailureProfitMultMax?: number;
  crossPlatformFailureAutoSafeOnLosses?: number;
  crossPlatformFailureCooldownBumpMs?: number;
  crossPlatformFailureCooldownBumpMaxMs?: number;
  crossPlatformFailureCooldownRecover?: number;
  crossPlatformFailureDepthUsdBump?: number;
  crossPlatformFailureDepthUsdBumpMax?: number;
  crossPlatformFailureDepthUsdRecover?: number;
  crossPlatformFailureForceSequentialMs?: number;
  crossPlatformFailureVwapTightenBps?: number;
  crossPlatformFailureMinProfitUsdBump?: number;
  crossPlatformFailureMinProfitUsdBumpMax?: number;
  crossPlatformFailureMinProfitUsdRecover?: number;
  crossPlatformFailureMinProfitBpsBump?: number;
  crossPlatformFailureMinProfitBpsBumpMax?: number;
  crossPlatformFailureMinProfitBpsRecover?: number;
  crossPlatformFailureSlippageTightenBps?: number;
  crossPlatformFailureNotionalUsdBump?: number;
  crossPlatformFailureNotionalUsdBumpMax?: number;
  crossPlatformFailureNotionalUsdRecover?: number;
  crossPlatformFailureDriftTightenBps?: number;
  crossPlatformFailureDepthUsageFactor?: number;
  crossPlatformFailureForceFokMs?: number;
  crossPlatformFailureMinDepthSharesBump?: number;
  crossPlatformFailureMinDepthSharesMax?: number;
  crossPlatformFailureMinDepthSharesRecover?: number;
  crossPlatformFailureTotalCostBpsBump?: number;
  crossPlatformFailureTotalCostBpsBumpMax?: number;
  crossPlatformFailureTotalCostBpsRecover?: number;
  crossPlatformFailurePreSubmitVwapTightenBps?: number;
  crossPlatformFailurePreSubmitLegSpreadTightenBps?: number;
  crossPlatformFailurePreSubmitLegCostSpreadTightenBps?: number;
  crossPlatformFailurePreSubmitProfitBpsBump?: number;
  crossPlatformFailurePreSubmitProfitUsdBump?: number;
  crossPlatformLimitOrders?: boolean;
  crossPlatformCancelOpenMs?: number;
  crossPlatformPostFillCheck?: boolean;
  crossPlatformFillCheckMs?: number;
  crossPlatformHedgeOnFailure?: boolean;
  crossPlatformHedgePredictOnly?: boolean;
  crossPlatformHedgeSlippageBps?: number;
  crossPlatformHedgeMinProfitUsd?: number;
  crossPlatformHedgeMinEdge?: number;
  crossPlatformHedgeForceOnPartial?: boolean;
  crossPlatformHedgeForceSlippageBps?: number;
  crossPlatformPostTradeHedge?: boolean;
  crossPlatformPostTradeHedgeMaxShares?: number;
  crossPlatformPostTradeHedgeForce?: boolean;
  crossPlatformPostTradeHedgeSlippageBps?: number;
  crossPlatformPostTradeNetHedge?: boolean;
  crossPlatformPostTradeNetHedgeMinShares?: number;
  crossPlatformPostTradeNetHedgeMaxShares?: number;
  crossPlatformPostTradeNetHedgeForce?: boolean;
  crossPlatformPostTradeNetHedgePredictOnly?: boolean;
  crossPlatformPostTradeNetHedgeSlippageBps?: number;
  crossPlatformDegradeMs?: number;
  crossPlatformDegradeSlippageBps?: number;
  crossPlatformDegradeStabilityBps?: number;
  crossPlatformDegradeChunkFactor?: number;
  crossPlatformDegradeChunkDelayMs?: number;
  crossPlatformDegradeForceSequential?: boolean;
  crossPlatformDegradeOnPostTrade?: boolean;
  crossPlatformDegradeExitMs?: number;
  crossPlatformDegradeExitSuccesses?: number;
  crossPlatformDegradeOrderType?: 'FOK' | 'FAK' | 'GTC' | 'GTD';
  crossPlatformDegradeDisableBatch?: boolean;
  crossPlatformDegradeLimitOrders?: boolean;
  crossPlatformDegradeUseFok?: boolean;
  crossPlatformNetRiskUsd?: number;
  crossPlatformNetRiskUsdPerToken?: number;
  crossPlatformNetRiskMinFactor?: number;
  crossPlatformNetRiskMaxFactor?: number;
  crossPlatformNetRiskDegradeFactor?: number;
  crossPlatformNetRiskScaleOnQuality?: boolean;
  crossPlatformNetRiskAutoTighten?: boolean;
  crossPlatformNetRiskTightenOnFailure?: number;
  crossPlatformNetRiskRelaxOnSuccess?: number;
  crossPlatformFallbackShrinkFactor?: number;
  crossPlatformFallbackMinFactor?: number;
  crossPlatformSingleLegTopN?: number;
  crossPlatformFailureProfitBps?: number;
  crossPlatformFailureProfitUsd?: number;
  crossPlatformFailureStabilityBps?: number;
  crossPlatformFailureStabilitySamplesAdd?: number;
  crossPlatformFailureStabilityIntervalAddMs?: number;
  crossPlatformFailureVwapDeviationBps?: number;
  crossPlatformFailureLegMinDepthUsdAdd?: number;
  crossPlatformFailureMaxVwapLevelsCut?: number;
  crossPlatformFailureMinNotionalUsdAdd?: number;
  crossPlatformFailureRetryDelayBumpMs?: number;
  crossPlatformSuccessRetryDelayTightenMs?: number;
  crossPlatformRetryDelayFloorMs?: number;
  crossPlatformRetryDelayCeilMs?: number;
  crossPlatformFailureProfitBpsBump?: number;
  crossPlatformFailureProfitBpsBumpMax?: number;
  crossPlatformFailureProfitBpsBumpRecover?: number;
  crossPlatformFailureStabilitySamplesMax?: number;
  crossPlatformFailureStabilityIntervalMaxMs?: number;
  crossPlatformFailureProfitUsdBump?: number;
  crossPlatformFailureProfitUsdBumpMax?: number;
  crossPlatformFailureProfitUsdBumpRecover?: number;
  crossPlatformFailureLegMinDepthUsdBump?: number;
  crossPlatformFailureLegMinDepthUsdBumpMax?: number;
  crossPlatformFailureLegMinDepthUsdBumpRecover?: number;
  crossPlatformFailureMinNotionalUsdBump?: number;
  crossPlatformFailureMinNotionalUsdBumpMax?: number;
  crossPlatformFailureMinNotionalUsdBumpRecover?: number;
  crossPlatformFailureProfitBpsCap?: number;
  crossPlatformFailureMaxRetriesCut?: number;
  crossPlatformFailureMaxRetriesMin?: number;
  crossPlatformMaxRetries?: number;
  crossPlatformRetryDelayMs?: number;
  crossPlatformCircuitMaxFailures?: number;
  crossPlatformCircuitWindowMs?: number;
  crossPlatformCircuitCooldownMs?: number;
  crossPlatformRetrySizeFactor?: number;
  crossPlatformRetryAggressiveBps?: number;
  crossPlatformRetryFactorMin?: number;
  crossPlatformRetryFactorMax?: number;
  crossPlatformRetryFactorUp?: number;
  crossPlatformRetryFactorDown?: number;
  crossPlatformSlippageDynamic?: boolean;
  crossPlatformSlippageFloorBps?: number;
  crossPlatformSlippageCeilBps?: number;
  crossPlatformFailureSlippageBumpBps?: number;
  crossPlatformSuccessSlippageTightenBps?: number;
  crossPlatformSuccessStabilityBps?: number;
  crossPlatformFailureChunkDelayBumpMs?: number;
  crossPlatformSuccessChunkDelayTightenMs?: number;
  crossPlatformFailureChunkFactorDown?: number;
  crossPlatformSuccessChunkFactorUp?: number;
  autoConfirmAll?: boolean;
  crossPlatformRequireWs?: boolean;
  crossPlatformMappingPath?: string;
  crossPlatformUseMapping?: boolean;
  alertWebhookUrl?: string;
  alertMinIntervalMs?: number;
  dependencyEnabled?: boolean;
  dependencyConstraintsPath?: string;
  dependencyPythonPath?: string;
  dependencyPythonScript?: string;
  dependencyMinProfit?: number;
  dependencyMaxLegs?: number;
  dependencyMaxNotional?: number;
  dependencyMinDepth?: number;
  dependencyMinDepthUsd?: number;
  dependencyDepthUsage?: number;
  dependencyFeeBps?: number;
  dependencyFeeCurveRate?: number;
  dependencyFeeCurveExponent?: number;
  dependencySlippageBps?: number;
  dependencyMaxIter?: number;
  dependencyOracleTimeoutSec?: number;
  dependencyTimeoutMs?: number;
  dependencyAllowSells?: boolean;
  multiOutcomeEnabled?: boolean;
  multiOutcomeMinOutcomes?: number;
  multiOutcomeMaxShares?: number;
  arbAutoExecute?: boolean;
  arbAutoExecuteValue?: boolean;
  arbExecuteTopN?: number;
  arbExecutionCooldownMs?: number;
  arbScanIntervalMs?: number;
  arbMaxMarkets?: number;
  arbOpportunitiesPath?: string;
  arbCommandPath?: string;
  arbSnapshotMax?: number;
  arbOrderbookConcurrency?: number;
  arbMarketsCacheMs?: number;
  arbWsMaxAgeMs?: number;
  arbWsRealtime?: boolean;
  arbWsRealtimeIntervalMs?: number;
  arbWsRealtimeMaxBatch?: number;
  arbWsRealtimeQuiet?: boolean;
  arbWsBoostMs?: number;
  arbWsBoostIntervalMs?: number;
  arbWsBoostMaxBatch?: number;
  arbWsBoostProfitMult?: number;
  crossPlatformWsBoostMs?: number;
  crossPlatformWsBoostIntervalMs?: number;
  crossPlatformWsBoostMaxBatch?: number;
  crossPlatformWsBoostProfitMult?: number;
  arbRequireWs?: boolean;
  arbWsHealthScoreMin?: number;
  arbMaxErrors?: number;
  arbErrorWindowMs?: number;
  arbPauseOnErrorMs?: number;
  arbPauseBackoff?: number;
  arbPauseMaxMs?: number;
  arbPauseRecoveryFactor?: number;
  arbDegradeMaxLevel?: number;
  arbDegradeFactor?: number;
  arbDegradeStabilityAdd?: number;
  arbDegradeTopNMin?: number;
  arbRecheckBumpMs?: number;
  arbRecheckBumpMaxMs?: number;
  arbRecheckBumpRecover?: number;
  arbWsHealthLogMs?: number;
  arbPreflightEnabled?: boolean;
  arbPreflightMaxAgeMs?: number;
  arbDepthUsage?: number;
  arbDepthLevels?: number;
  arbMinDepthUsd?: number;
  arbMinTopDepthShares?: number;
  arbMinTopDepthUsd?: number;
  arbTopDepthUsage?: number;
  arbMinNotionalUsd?: number;
  arbMinProfitUsd?: number;
  arbMinProfitBps?: number;
  arbMinProfitImpactMult?: number;
  arbMaxVwapDeviationBps?: number;
  arbRecheckDeviationBps?: number;
  arbMaxVwapLevels?: number;
  arbStabilityRequired?: boolean;
  arbStabilityMinCount?: number;
  arbStabilityWindowMs?: number;
  arbRequireWsHealth?: boolean;
  arbWsHealthMaxAgeMs?: number;
  arbWsHealthFailureBumpMs?: number;
  arbWsHealthRecoveryMs?: number;
  predictFeeBps?: number;
  polymarketGammaUrl?: string;
  polymarketClobUrl?: string;
  polymarketMaxMarkets?: number;
  polymarketFeeBps?: number;
  polymarketFeeRateUrl?: string;
  polymarketFeeRateCacheMs?: number;
  polymarketFeeCurveRate?: number;
  polymarketFeeCurveExponent?: number;
  polymarketFunderAddress?: string;
  polymarketSignatureType?: number;
  polymarketWsEnabled?: boolean;
  polymarketWsUrl?: string;
  polymarketWsCustomFeature?: boolean;
  polymarketWsInitialDump?: boolean;
  polymarketWsStaleMs?: number;
  polymarketWsResetOnReconnect?: boolean;
  polymarketCacheTtlMs?: number;
  predictWsEnabled?: boolean;
  predictWsUrl?: string;
  predictWsApiKey?: string;
  predictWsTopicKey?: 'token_id' | 'condition_id' | 'event_id';
  predictWsStaleMs?: number;
  predictWsResetOnReconnect?: boolean;
  predictAutoSetApprovals?: boolean;
  predictCollateralBufferBps?: number;
  predictBuyInsufficientCooldownMs?: number;
  predictChainId?: number;
  predictSafeMaxSpread?: number;
  predictSafeMinL1Notional?: number;
  predictSafeMinL2Notional?: number;
  predictSafeMinL2ToL1Ratio?: number;
  predictSafeMinPrice?: number;
  predictSafeMaxPrice?: number;
  predictSafeMaxLevelGap?: number;
  predictFillPauseMs?: number;
  predictUnsafeBookPauseMs?: number;
  predictPositionLossLimitAbs?: number;
  predictPositionLossLimitRatio?: number;
  predictPositionLossPauseMs?: number;
  polymarketPrivateKey?: string;
  polymarketApiKey?: string;
  polymarketApiSecret?: string;
  polymarketApiPassphrase?: string;
  polymarketChainId?: number;
  polymarketAutoDeriveApiKey?: boolean;
  polymarketRewardMinFitScore?: number;
  polymarketRewardMinDailyRate?: number;
  polymarketRewardRequireFit?: boolean;
  polymarketRewardRequireEnabled?: boolean;
  polymarketRewardPauseMs?: number;
  polymarketRewardSizeCapMultiplier?: number;
  polymarketRewardCrowdingPenaltyStart?: number;
  polymarketRewardCrowdingPenaltyMax?: number;
  polymarketPostOnlyMinHitRate?: number;
  polymarketPostOnlyMinAttempts?: number;
  polymarketPostOnlyWindowMs?: number;
  polymarketPostOnlyPauseMs?: number;
  polymarketAdversePressureThreshold?: number;
  polymarketAdverseImbalanceThreshold?: number;
  polymarketAdverseDepthSpeedBps?: number;
  polymarketPositionLossLimitAbs?: number;
  polymarketPositionLossLimitRatio?: number;
  polymarketPositionLossPauseMs?: number;
  opinionOpenApiUrl?: string;
  opinionApiKey?: string;
  opinionMaxMarkets?: number;
  opinionFeeBps?: number;
  opinionPythonPath?: string;
  opinionPythonScript?: string;
  opinionPrivateKey?: string;
  opinionChainId?: number;
  opinionHost?: string;
  opinionWsEnabled?: boolean;
  opinionWsUrl?: string;
  opinionWsHeartbeatMs?: number;
  opinionWsStaleMs?: number;
  opinionWsResetOnReconnect?: boolean;
  marketTokenIds?: string[];
  refreshInterval: number;
  enableTrading: boolean;
}

export interface MarketOutcome {
  name: string;
  indexSet: number;
  status: 'WON' | 'LOST' | 'OPEN' | 'CANCELLED';
  onChainId: string;
}

export interface Market {
  token_id: string;
  question: string;
  description?: string;
  condition_id?: string;
  event_id?: string;
  market_url?: string;
  market_slug?: string;
  outcome?: string;
  end_date?: string;
  venue?: 'predict' | 'polymarket';
  is_neg_risk: boolean;
  is_yield_bearing: boolean;
  fee_rate_bps: number;
  volume_24h?: number;
  liquidity_24h?: number;
  // Outcomes array containing all outcome tokens
  outcomes?: MarketOutcome[];
  // Price aggregation from orderbook
  best_bid?: number;
  best_ask?: number;
  spread_pct?: number;
  total_orders?: number;
  polymarket_rewards_enabled?: boolean;
  polymarket_reward_min_size?: number;
  polymarket_reward_max_spread?: number;
  polymarket_reward_daily_rate?: number;
  polymarket_reward_hourly_rate?: number;
  polymarket_reward_epoch?: number;
  polymarket_reward_in_game_multiplier?: number;
  polymarket_accepting_orders?: boolean;
  polymarket_tick_size?: number;
  polymarket_enable_order_book?: boolean;
  // Liquidity Points Activation Rules
  // These fields control when orders qualify for liquidity points
  liquidity_activation?: LiquidityActivation;
}

/**
 * Liquidity activation rules for a market
 * Orders must meet these criteria to earn liquidity points
 *
 * Based on Predict.fun UI:
 * - Min. shares: 100 (minimum number of shares)
 * - Max spread: ±6¢ (6 cents = $0.06)
 */
export interface LiquidityActivation {
  // Minimum shares to qualify for points
  min_shares?: number;
  // Maximum spread to qualify for points (in cents, e.g., 6 = $0.06)
  max_spread_cents?: number;
  // Maximum spread as decimal (e.g., 0.06)
  max_spread?: number;
  // Whether points are currently active for this market
  active?: boolean;
  // Description of the requirements
  description?: string;
}

export interface OrderbookEntry {
  price: string;
  shares: string;
  creator?: string;
  orderbook_id?: string;
  order_type?: 'LIMIT' | 'MARKET';
}

export interface Orderbook {
  token_id: string;
  bids: OrderbookEntry[];
  asks: OrderbookEntry[];
  best_bid?: number;
  best_ask?: number;
  spread?: number;
  spread_pct?: number;
  mid_price?: number;
}

export interface Order {
  id?: string;
  order_hash: string;
  token_id: string;
  maker: string;
  signer?: string;
  order_type: 'LIMIT' | 'MARKET';
  side: 'BUY' | 'SELL';
  price: string;
  shares: string;
  is_neg_risk: boolean;
  is_yield_bearing: boolean;
  fee_rate_bps?: number;
  signature?: string;
  status: 'OPEN' | 'FILLED' | 'CANCELED';
  timestamp: number;
}

export interface Position {
  token_id: string;
  question: string;
  yes_amount: number;
  no_amount: number;
  total_value: number;
  avg_entry_price: number;
  current_price: number;
  pnl: number;
  tokenId?: string;
  market?: { tokenId?: string; question?: string };
  outcome?: string;
  side?: string;
  amount?: number;
  shares?: number;
  size?: number;
  value?: number;
  avg_price?: number;
  avgEntryPrice?: number;
  currentPrice?: number;
}

export interface MarketMakerState {
  markets: Map<string, Market>;
  orderbooks: Map<string, Orderbook>;
  openOrders: Map<string, Order>;
  positions: Map<string, Position>;
  lastUpdate: number;
}
